const msg = {
  messageDefault: 'この項目は必須です。',
  createPassword: 'パスワードを設定しました',
  resetPassword: 'パスワードを変更しました',
  fileTypeErr: 'ファイルの形式が適切ではありません',
  fileSizeErr: 'ファイルの容量は10 Mbを超えました。',
  passwordNotSame: 'パスワードが一致しません',
  loginFail: 'ユーザー名またはパスワードが間違っています',
  systemFail: 'システムエラー',
  loginSuccess: '正常にログインしました。',
  wrongEmail: 'Eメールアドレスが不正です。',
  createUser: 'ユーザー作成に成功しました。',
  updateUser: 'ユーザーの更新が完了しました。',
  deleteUser: 'ユーザーの削除に成功しました。',
  sendResetPassword: 'Eメールに情報が送信されました。',
  passwordShort: 'パスワードは8文字必要です',
  dateInvalid: 'dateInvalid',
  studioConfirmDetele: 'を削除しても宜しいでしょうか？',
  studioDeleteSuccess: 'を削除しました。',
  studioCreateSuccess: 'を作成しました。',
  studioEditSuccess: 'を編集しました。',
  staffConfirmDetele: 'を削除しても宜しいですか？',
  staffDeleteSuccess: 'を削除しました。',
  staffCreateSuccess: 'を作成しました。',
  staffEditSuccess: 'の情報を編集しました。',
  startDatePlaceholderText: '開始日',
  endDatePlaceholderText: '終了日',
  staffScheduleUdateSuccess: '撮影スケジュールを更新しました',
  warningHairmake: 'ヘアメイクを選択してください',
  warningPhotographer: 'カメラマンを選択してください',
  createPlans: 'を作成しました',
  updatePlans: 'を更新しました',
  deletPlans: 'を削除しました',
  plansConfirmDetele: 'を削除しても宜しいでしょうか？',
  createPlanOptions: 'を作成しました',
  updatePlanOptions: 'を更新しました',
  deletPlanOptions: 'を削除しました',
  planOptionsConfirmDetele: 'を削除しても宜しいでしょうか？',
  createCostume: 'を作成しました。',
  updateCostume: 'を編集しました。',
  deleteCostume: 'を削除しました。',
  changeStatusBooking: '予約情報をキャンセルしました。',
  editBooking: '予約情報を編集しました。',
  existDate: 'この日程はすでに予約済みです。',
  createCoupon: 'を作成しました。',
  updateCoupon: 'を編集しました。',
  deleteCoupon: 'を削除しました。',
  createNews: 'を作成しました。',
  updateNews: 'を編集しました。',
  deleteNews: 'を削除しました。',
  couponConfirmDetele: 'を削除しても宜しいでしょうか？',
  costumeLocksDeleteMessage: 'この衣装ロックを削除しても宜しいですか？',
  createCostumeLocks: '衣装ロックを作成しました',
  updateCostumeLocks: '衣装ロックを更新しました',
  deleteCostumeLocks: '衣装ロックを削除しました',
  createFAQ: 'FAQ情報を作成しました。',
  updateFAQ: 'FAQ情報を編集しました。',
  deleteFAQ: 'FAQ情報を削除しました。',
  confirmDeleteFAQ: 'FAQ情報を削除してもよろしいですか？',
  createReviews: 'レビューを作成しました',
  updateReviews: 'レビューを編集しました',
  deleteReviews: 'レビューを削除しました',
  updateCustomer: 'の情報を編集しました',
  deleteCustomer: 'を削除しました',
  confirmDeleteCustomer: 'を削除しても宜しいですか？',
  updateBookingPhoto: '写真を更新しました。',
  deleteBookingPhoto: '写真を削除しました。',
  confirmDeleteBookingPhoto: '削除してもよろしいですか？',
  noImageSelect: 'あなたはまだ写真を選択していません',
  updateStaffPays: 'カメラマン/ヘアメイクの報酬を更新しました。',
  deleteStaffPays: 'カメラマン/ヘアメイクの報酬を削除しました。',
  confirmStaffPays: '確定処理を実行しました。',
  confirmAllStaffPays: '報酬を一括確定しました。',
  confirmDeleteStaffPays: 'カメラマン/ヘアメイクの報酬を削除しても宜しいですか？',
  messageConfirmAllStaffPays: 'チェックした報酬を一括確定しても宜しいですか？',
  messageConfirmCancelOrder:'の受注をキャンセルしますか？ ',
  cancelOrderSuccess:'の受注をキャンセルしました。',
  updateOrderSuccess:'の受注を更新しました。',
  createOrderSuccess:'の受注を作成しました。',
  bookingCodeNotFound:'指定の予約が存在しません。',
  costumeIdNotFound:'指定の衣装が存在しません。',
  bookingHaveNoImage:'指定の予約に写真が存在しません。',
  failCountProduct:'配送先に指定されている個数が受注の個数を超えています。',
  statuBookingNotContain:'予約の撮影が完了していません。',
  addressDataNotFound:' 住所の情報が存在しません。',
  couponNotFound: 'このクーポンは利用できません。',
  couponSafe: 'このクーポンは利用可能です。',
  confirmDeleteCustomerDelivery: "配送先情報を削除して宜しいですか？",
  deleteCustomerDelivery: "配送先情報を削除しました",
  createCustomerDelivery: "配送先情報を作成しました",
  editCustomerDelivery: "配送先情報を更新しました",
  couponSafe: 'このクーポンは利用可能です。',
  confirmDeleteProduct: 'を削除してもよろしいですか？',
  deleteProduct: 'を削除しました。',
  editProduct: 'を編集しました。',
  createProduct: 'を作成しました。',
  confirmDeleteBookingProduct: '商品情報を削除してもよろしいですか？',
  createBookingProduct: '商品情報を作成しました',
  updateBookingProduct: '商品情報を更新しました',
  deleteBookingProduct: '商品情報を削除しました。',
  confirmCancelOrderDeliveryBookingProducts: 'キャンセルしてもよろしいですか？',
  confirmReturnOrderDeliveryBookingProducts: '返品してもよろしいですか？',
  confirmDeleteOrderDeliveryBookingProducts: 'この商品を削除しますか ?',
};

export { msg };
