import Login from './Login.jsx';
import StaffLogin from './StaffLogin.jsx';
import ForgotPasswordPage from './ForgotPasswordPage.jsx';
import StaffForgotPasswordPage from './StaffForgotPasswordPage.jsx';
import {ListUser, CreateUser, EditUser} from './users';
import {ListStudio, CreateStudio, EditStudio} from './studio';
import {CreatePassword, ResetPassword} from './password';
import {ListPlans, CreatePlans, EditPlans} from './shooting/plans';
import {ListPlanOptions, CreatePlanOptions, EditPlanOptions} from './shooting/plan-options';
import {StaffCreatePassword, StaffResetPassword} from './staff-password';
import {ListStaff, CreateStaff, EditStaff} from './staff';
import {ListStaffSchedule, EditStaffSchedule} from './staff-schedule';
import {ListBooking, EditBooking} from './booking';
import {ListCostume, CreateCostume, EditCostume} from './costume';
import {ListCostumeLocks, CreateCostumeLocks, EditCostumeLocks} from './costume-lock';
import {ListCoupon, CreateCoupon, EditCoupon} from './coupons';
import {ListNews, CreateNews, EditNews} from './news';
import {ListFAQ, CreateFAQ, EditFAQ} from './faq';
import {ListCustomer, EditCustomer} from './customer';
import {ListBookingPhoto, DeleteBookingPhoto, DownloadBookingPhoto} from './booking-photo';
import {ListReview, CreateReview, EditReview} from './reviews';
import {ListStaffPay, EditStaffPay} from './staff-pay';
import {ListStaffBooking, DetailStaffBooking} from './staff-booking';
import {ListOrder, CreateOrder, EditOrder} from './order';
import {ListProduct, CreateProduct, EditProduct} from './product';
import {ListStaffBookingPhoto, DeleteStaffBookingPhoto, DownloadStaffBookingPhoto} from './staff-booking-photo';
import {ListEarning} from './earning';
import {Dashboard} from './home';
import {ListStaffPayForStaff, DetailStaffPayForStaff} from './staff-pay-for-staff';
import {StaffDashboard} from './staff-home';

export {StaffCreatePassword, StaffResetPassword, Login, ListUser, CreateUser, EditUser, ListStudio, CreateStudio, CreatePassword, ResetPassword, EditStudio, ForgotPasswordPage, StaffForgotPasswordPage, ListStaff, CreateStaff, EditStaff, StaffLogin, ListPlans, CreatePlans, EditPlans, ListPlanOptions, CreatePlanOptions, EditPlanOptions, ListCostume, CreateCostume, EditCostume, ListStaffSchedule, EditStaffSchedule, ListCoupon, CreateCoupon, EditCoupon, ListBooking, EditBooking, ListFAQ, CreateFAQ, EditFAQ, ListCostumeLocks, CreateCostumeLocks, EditCostumeLocks, ListNews, CreateNews, EditNews, ListCustomer, EditCustomer, ListBookingPhoto, DeleteBookingPhoto, DownloadBookingPhoto, ListStaffBooking, DetailStaffBooking, ListStaffPay, EditStaffPay, ListStaffBookingPhoto, DeleteStaffBookingPhoto, DownloadStaffBookingPhoto, ListReview, CreateReview, EditReview, ListStaffPayForStaff, DetailStaffPayForStaff, ListProduct, CreateProduct, EditProduct, ListOrder, CreateOrder, EditOrder, ListEarning, Dashboard, StaffDashboard};