import Auth from 'api/auth';
import Users from 'api/users';
import Studios from 'api/studios';
import System from 'api/system';
import Staff from 'api/staff';
import Plans from 'api/plans';
import PlanOptions from 'api/planOptions';
import StaffSchedule from 'api/staff-schedule';
import Costumes from 'api/costumes';
import CostumeLocks from 'api/costumeLocks';
import Booking from 'api/booking';
import Coupons from 'api/coupons';
import News from 'api/news';
import FAQ from 'api/faq';
import Customer from 'api/customer';
import BookingPhoto from 'api/bookingPhoto';
import Reviews from 'api/reviews';
import StaffPays from './staffPays';
import StaffBooking from 'api/staffBooking';
import Order from 'api/order';
import Earning from 'api/earning';
import CustomerDelivery from 'api/customer-delivery';
import Product from 'api/product';
import StaffPayForStaff from 'api/staffPayForStaff';

export {Auth, Users, Studios, System, Staff, Plans, PlanOptions, Costumes, StaffSchedule, CostumeLocks, Coupons, News, Booking, FAQ, Customer, Reviews, BookingPhoto, StaffBooking, StaffPays, StaffPayForStaff, Product, CustomerDelivery, Order, Earning};
